image:
  file: .gitpod.Dockerfile

tasks:
  - init: sdk use java 16.0.1.hs-adpt
    command: echo "replace me with something that should run on every start. It could be cd javafx-template; mvn compile"

ports:
  # used by virtual desktop and vnc, supports JavaFX
  - port: 6080
