@startuml
!theme amiga
Component fxui {
  package "gr2232.ui" 

} 
fxui ..> [javafx]
fxui ..> [fxml]

Component core {
  package "gr2232.core"
  package "gr2232.json"

}

gr2232.json ..> [jackson]

Component rest {
  package "gr2232.rest" 
} 

rest ..> [springboot]
gr2232.rest ..> gr2232.core
gr2232.rest ..> gr2232.json


gr2232.ui ..> gr2232.core
gr2232.ui ..> gr2232.json
@enduml