@startuml
group Admin registers new units/booths
!theme amiga
actor User #red
participant "~#getNewBoothButton:Button" as A
participant "fxui" as B
participant "core" as C
participant "rest" as D
participant "server" as E


User -> A: Click "Submit"
A -> B: void getNewBooth()
B --> B: void getInputValues()
B -> C: void createTempUnit() 

B -> D: POST[serialize(input)]
D -> E: save to the database
E --> D: save is successful

D --> B: response:200 body: true
B --> C: add the Unit to unitList
B --> B: void clearFields()
end
@enduml